[package]
name = "fetchy"
version = "0.13.12"
edition = "2021"
description = "Quick packages installer"
license = "Apache-2.0"
repository = "https://github.com/ClementNerma/Fetchy"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
comfy-table = "7.1.3"
dialoguer = { version = "0.11.0", default-features = false }
dirs = "5.0.1"
flate2 = "1.0.35"
indicatif = "0.17.9"
jiff = { version = "0.1.14", features = ["serde"] }
log = { version = "0.4.22", features = ["std"] }
openssl-sys = { version = "0.9.104", features = ["vendored"] }
owo-colors = "4.1.0"
parsy = { version = "0.9.1", features = ["error-reporting"] }
paste = "1.0.15"
rapidfuzz = "0.5.0"
regex = "1.11.1"
reqwest = "0.12.9"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tar = "0.4.43"
tempfile = "3.14.0"
tokio = { version = "1.41.1", features = ["fs", "macros", "rt-multi-thread"] }
xz = "0.1.0"
zip = { version = "2.2.1", default-features = false, features = [
    "deflate",
    "deflate64",
] }
