[package]
name = "fetchy"
version = "0.14.6"
edition = "2024"
description = "Quick packages installer"
license = "Apache-2.0"
repository = "https://github.com/ClementNerma/Fetchy"

[dependencies]
anyhow = "1.0.100"
bzip2 = "0.6.1"
clap = { version = "4.5.50", features = ["derive"] }
colored = "3.0.0"
comfy-table = "7.2.1"
dialoguer = { version = "0.12.0", default-features = false }
dirs = "6.0.0"
flate2 = "1.1.5"
indicatif = "0.18.1"
jiff = { version = "0.2.15", features = ["serde"] }
log = { version = "0.4.28", features = ["std"] }
parsy = { version = "0.15.8", features = ["error-reporting"] }
paste = "1.0.15"
rapidfuzz = "0.5.0"
regex = "1.12.2"
reqwest = { version = "0.12.24", default-features = false, features = [
    "http2",
    "gzip",
    "rustls-tls",
] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tar = "0.4.44"
tempfile = "3.23.0"
tokio = { version = "1.48.0", features = ["fs", "macros", "rt-multi-thread"] }
xz = "0.1.0"
zip = { version = "6.0.0", default-features = false, features = [
    "deflate",
    "deflate64",
] }
