[package]
name = "fetchy"
version = "0.14.0"
edition = "2021"
description = "Quick packages installer"
license = "Apache-2.0"
repository = "https://github.com/ClementNerma/Fetchy"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
colored = "2.2.0"
comfy-table = "7.1.3"
dialoguer = { version = "0.11.0", default-features = false }
dirs = "5.0.1"
flate2 = "1.0.35"
indicatif = "0.17.9"
jiff = { version = "0.1.19", features = ["serde"] }
log = { version = "0.4.22", features = ["std"] }
openssl-sys = { version = "0.9.104", features = ["vendored"] }
parsy = { version = "0.9.1", features = ["error-reporting"] }
paste = "1.0.15"
rapidfuzz = "0.5.0"
regex = "1.11.1"
reqwest = "0.12.12"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
tar = "0.4.43"
tempfile = "3.15.0"
tokio = { version = "1.42.0", features = ["fs", "macros", "rt-multi-thread"] }
xz = "0.1.0"
zip = { version = "2.2.2", default-features = false, features = [
    "deflate",
    "deflate64",
] }
