[package]
name = "fetchy"
version = "0.1.3"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
async-compression = { version = "0.3.15", features = ["gzip"] }
async_zip = "0.0.9"
clap = { version = "4.0.27", features = ["derive"] }
colored = "2.0.0"
dialoguer = { version = "0.10.2", default-features = false }
dirs = "4.0.0"
futures-util = "0.3.25"
indicatif = "0.17.2"
once_cell = "1.16.0"
pomsky = "0.7.0"
pomsky-macro = "0.7.0"
regex = "1.7.0"
reqwest = { version = "0.11.13", features = ["stream"]}
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.89"
tempfile = "3.3.0"
tokio = { version = "1.22.0", features = ["macros", "rt-multi-thread", "fs"] }
tokio-tar = "0.3.0"
