[package]
name = "fetchy"
version = "0.12.3"
edition = "2021"
description = "Quick packages installer"
license = "Apache-2.0"
repository = "https://github.com/ClementNerma/Fetchy"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
colored = "2.1.0"
dialoguer = { version = "0.11.0", default-features = false }
dirs = "5.0.1"
flate2 = "1.0.34"
glob = "0.3.1"
indicatif = "0.17.8"
openssl-sys = { version = "0.9.104", features = ["vendored"] }
parsy = "0.7.1"
paste = "1.0.15"
rayon = "1.10.0"
regex = "1.11.0"
reqwest = { version = "0.12.8", features = ["blocking"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tar = "0.4.42"
tempfile = "3.13.0"
unicode-width = "0.2.0"
xz2 = "0.1.7"
zip = "2.2.0"
