[package]
name = "fetchy"
version = "0.9.1"
edition = "2021"
description = "Quick packages installer"
license = "Apache-2.0"
repository = "https://github.com/ClementNerma/Fetchy"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.18", features = ["derive"] }
colored = "2.1.0"
dialoguer = { version = "0.11.0", default-features = false }
dirs = "5.0.1"
flate2 = "1.0.28"
glob = "0.3.1"
indicatif = "0.17.7"
openssl-sys = { version = "0.9.99", features = ["vendored"] }
parsy = "0.5.5"
paste = "1.0.14"
regex = "1.10.3"
reqwest = { version = "0.11.24", features = ["blocking"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
tar = "0.4.40"
tempfile = "3.10.0"
unicode-width = "0.1.11"
xz2 = "0.1.7"
zip = "0.6.6"
