[package]
name = "fetchy"
version = "0.9.2"
edition = "2021"
description = "Quick packages installer"
license = "Apache-2.0"
repository = "https://github.com/ClementNerma/Fetchy"

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.2", features = ["derive"] }
colored = "2.1.0"
dialoguer = { version = "0.11.0", default-features = false }
dirs = "5.0.1"
flate2 = "1.0.28"
glob = "0.3.1"
indicatif = "0.17.8"
openssl-sys = { version = "0.9.101", features = ["vendored"] }
parsy = "0.5.5"
paste = "1.0.14"
regex = "1.10.3"
reqwest = { version = "0.11.25", features = ["blocking"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tar = "0.4.40"
tempfile = "3.10.1"
unicode-width = "0.1.11"
xz2 = "0.1.7"
zip = "0.6.6"
