[package]
name = "fetchy"
version = "0.13.6"
edition = "2021"
description = "Quick packages installer"
license = "Apache-2.0"
repository = "https://github.com/ClementNerma/Fetchy"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
colored = "2.1.0"
comfy-table = "7.1.1"
dialoguer = { version = "0.11.0", default-features = false }
dirs = "5.0.1"
flate2 = "1.0.34"
indicatif = "0.17.8"
jiff = { version = "0.1.13", features = ["serde"] }
log = { version = "0.4.22", features = ["std"] }
openssl-sys = { version = "0.9.104", features = ["vendored"] }
parsy = "0.7.1"
paste = "1.0.15"
rapidfuzz = "0.5.0"
regex = "1.11.0"
reqwest = "0.12.8"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.129"
tar = "0.4.42"
tempfile = "3.13.0"
tokio = { version = "1.40.0", features = ["fs", "macros", "rt-multi-thread"] }
xz = "0.1.0"
zip = { version = "2.2.0", default-features = false, features = [
    "deflate",
    "deflate64",
] }
