[package]
name = "fetchy"
version = "0.7.0"
edition = "2021"
description = "Quick packages installer"
license = "Apache-2.0"
repository = "https://github.com/ClementNerma/Fetchy"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.4", features = ["derive"] }
colored = "2.0.4"
dialoguer = { version = "0.11.0", default-features = false }
dirs = "5.0.1"
flate2 = "1.0.27"
glob = "0.3.1"
indicatif = "0.17.7"
openssl-sys = { version = "0.9.93", features = ["vendored"] }
parsy = { path = "../Parsy" }
paste = "1.0.14"
regex = "1.9.5"
reqwest = { version = "0.11.20", features = ["blocking"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
tar = "0.4.40"
tempfile = "3.8.0"
unicode-width = "0.1.11"
xz2 = "0.1.7"
zip = "0.6.6"
