[package]
name = "fetchy-pkgs"
version = "0.4.0"
edition = "2021"
description = "Quick packages installer"
license = "Apache-2.0"
repository = "https://github.com/ClementNerma/Fetchy"

[[bin]]
name = "fetchy"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.75"
async-compression = { version = "0.4.1", features = ["tokio", "gzip", "xz"] }
async-recursion = "1.0.4"
clap = { version = "4.3.23", features = ["derive"] }
colored = "2.0.4"
dialoguer = { version = "0.10.4", default-features = false }
dirs = "5.0.1"
futures-util = "0.3.28"
glob = "0.3.1"
indicatif = "0.17.6"
once_cell = "1.18.0"
openssl-sys = { version = "0.9.91", features = ["vendored"] }
paste = "1.0.14"
pomsky-macro = "0.10.0"
regex = "1.9.3"
reqwest = { version = "0.11.19", features = ["stream"] }
ron = "0.8.1"
serde = { version = "1.0.185", features = ["derive"] }
serde_json = "1.0.105"
tar = "0.4.40"
tempfile = "3.8.0"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread", "fs"] }
unicode-width = "0.1.10"
zip = "0.6.6"

[profile.dist]
inherits = "release"
lto = "thin"
