[package]
name = "fetchy"
version = "0.1.16"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
async-compression = { version = "0.3.15", features = ["tokio", "gzip", "xz"] }
async_zip = { version = "0.0.11", features = ["fs"] }
clap = { version = "4.1.4", features = ["derive"] }
colored = "2.0.0"
dialoguer = { version = "0.10.3", default-features = false }
dirs = "4.0.0"
futures-util = "0.3.26"
indicatif = "0.17.3"
once_cell = "1.17.0"
pomsky = "0.9.0"
pomsky-macro = "0.9.0"
regex = "1.7.1"
reqwest = { version = "0.11.14", features = ["stream"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.92"
tempfile = "3.3.0"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread", "fs"] }
tokio-tar = "0.3.0"
