[package]
name = "fetchy-pkgs"
version = "0.2.2"
edition = "2021"
description = "Quick packages installer"
license = "Apache-2.0"
repository = "https://github.com/ClementNerma/Fetchy"

[[bin]]
name = "fetchy"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.70"
async-compression = { version = "0.3.15", features = ["tokio", "gzip", "xz"] }
async-recursion = "1.0.4"
clap = { version = "4.2.4", features = ["derive"] }
colored = "2.0.0"
dialoguer = { version = "0.10.4", default-features = false }
dirs = "4.0.0"
futures-util = "0.3.28"
indicatif = "0.17.3"
once_cell = "1.17.1"
openssl-sys = { version = "0.9.86", features = ["vendored"] }
pomsky-macro = "0.9.0"
regex = "1.8.1"
reqwest = { version = "0.11.16", features = ["stream"] }
ron = "0.8.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
tempfile = "3.5.0"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread", "fs"] }
tokio-tar = "0.3.0"
zip = "0.6.4"

[profile.dist]
inherits = "release"
lto = "thin"
